development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:2764ec1f283b6b3bad5013c695c934ea@crestfish.redistogo.com:11686/
  channel_prefix: tdwchat_production
