development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:64e07a922a4bb562e2533ecb27da9baa@pike.redistogo.com:10309/
  channel_prefix: tdwchat_production
